### ISSUE TITLE
Failure to build from Hackage

### ISSUE THREAD

**Issue by mouse07410** [MarcWeber/hasktags#90]
```text
$ cabal install hasktags --overwrite-policy=always -w ghc-9.6.2
Resolving dependencies...
Build profile: -w ghc-9.6.2 -O2
In order, the following will be built (use -v for more details):
 - json-0.10 (lib:json) (requires build)
 - microlens-0.4.13.1 (lib) (requires build)
 - prettyprinter-1.7.1 (lib) (requires build)
 - microlens-th-0.4.3.13 (lib) (requires build)
 - microlens-mtl-0.2.0.3 (lib) (requires build)
 - microlens-ghc-0.4.14.1 (lib) (requires build)
 - prettyprinter-ansi-terminal-1.1.3 (lib) (requires build)
 - microlens-platform-0.4.3.3 (lib) (requires build)
 - optparse-applicative-0.18.1.0 (lib) (requires build)
 - hasktags-0.72.0 (lib) (requires build)
 - hasktags-0.72.0 (exe:hasktags) (requires build)
Starting     microlens-0.4.13.1 (lib)
.  .  .
Installing   optparse-applicative-0.18.1.0 (lib)
Completed    optparse-applicative-0.18.1.0 (lib)
Starting     hasktags-0.72.0 (exe:hasktags)
Building     hasktags-0.72.0 (exe:hasktags)

Failed to build exe:hasktags from hasktags-0.72.0.
Build log ( /Users/ur20980/.cabal/logs/ghc-9.6.2/hsktgs-0.72.0-7d29dda4.log ):
Configuring executable 'hasktags' for hasktags-0.72.0..
Preprocessing executable 'hasktags' for hasktags-0.72.0..
Building executable 'hasktags' for hasktags-0.72.0..
[1 of 2] Compiling Paths_hasktags   ( dist/build/hasktags/autogen/Paths_hasktags.hs, dist/build/hasktags/hasktags-tmp/Paths_hasktags.dyn_o )
[2 of 2] Compiling Main             ( src/Main.hs, dist/build/hasktags/hasktags-tmp/Main.dyn_o )

src/Main.hs:12:41: error:
    Module ‘Options.Applicative.Help.Pretty’ does not export ‘text’
   |
12 | import Options.Applicative.Help.Pretty (text, line)
   |                                         ^^^^
Error: cabal: Failed to build exe:hasktags from hasktags-0.72.0. See the build
log above for details.
```

I'm getting the same failure trying to build with GHC-9.2.8.

In case it matters:
- MacOS Ventura 13.4
- Cabal-3.10.1.0
- GHC-9.6.2, GHC-9.2.8

**Comment by jhenahan** [comment]
Oh, huh. I guess `optparse-applicative` must have updated. I'll have a look. Thanks for the report.

**Comment by mouse07410** [comment]
Any luck so far?

**Comment by mouse07410** [comment]
Any luck...?

**Comment by jhenahan** [comment]
Yes, I'm terribly sorry. A fix was merged in #91, and I just haven't pushed the button to publish the new version. I'll get that out tomorrow. Cc: @andreasabel Sorry to you as well for not getting your fix released in a timely fashion.

**Comment by andreasabel** [comment]
I had to revise to `json < 0.12` so that I could ask for reenabling `hasktags` in stackage nightly (which has `json-0.11`).
- https://github.com/commercialhaskell/stackage/pull/7087
